'use client';

import { useState } from 'react';
import { ArrowRight, Check, ChefHat, CircleHelp, Globe2, LockKeyhole, Sparkles, Utensils, X } from 'lucide-react';

type Lang = 'ko' | 'fr';
const copy = {
  ko: { eyebrow: '?꾨옉???앹궗 ?덉젅 寃뚯엫', hero: '? Table!', sub: '?뚯씠釉????묒? 留ㅻ꼫濡?n?꾨옉?ㅼ? ??媛源뚯썙?몄슂.', start: '寃뚯엫 ?쒖옉?섍린', tips: '?꾩?????, progress: '泥?踰덉㎏ ?먰떚耳?誘몄뀡', question: '鍮듭? ?대뵒???볦븘???좉퉴??', hint: '?좉퉸! ?꾨옉???앺긽?먯꽌??鍮듬룄 ?먭린 ?먮━媛 ?덉뼱??', correct: 'C?셞st parfait!', correctSub: '?뺣떟?댁뿉?? ?꾨옉?ㅼ떇 ?앹궗??泥リ구?뚯쓣 ???대뵒?좎뼱??', tipTitle: '?꾩????앹궗 轅??, tip: '鍮듭? ?묒떆 ?꾧? ?꾨땲???뚯씠釉??쇱そ??諛붾줈 ?볦븘?? 鍮듭쓣 移쇰줈 ?먮Ⅴ湲곕낫???먯쑝濡??쒖엯???쇱뼱 癒밸뒗 寃껊룄 湲곗뼲??二쇱꽭??', next: '?ㅼ쓬 誘몄뀡 以鍮꾪븯湲?, wrong: '?꾩쭅 議곌툑 ?꾩돩?뚯슂', tryAgain: '?ㅼ떆 ?앷컖??蹂쇨퉴??', options: ['?묒떆 ??, '?뚯씠釉??쇱そ', '?낇궓 ??] },
  fr: { eyebrow: 'JEU D?쇒뎆IQUETTE FRAN횉AISE', hero: '? Table!', sub: 'Un petit geste 횪 table,\nun grand pas vers la France.', start: 'Commencer le jeu', tips: 'Conseils locaux', progress: 'MISSION 01 쨌 횋TIQUETTE', question: 'O첫 doit-on poser le pain ?', hint: 'Un instant ! M챗me le pain a sa place 횪 table en France.', correct: 'C?셞st parfait!', correctSub: 'Bonne r챕ponse. Vous commencez tr챔s bien votre repas fran챌ais.', tipTitle: 'Le conseil d?셵n ami fran챌ais', tip: 'On pose le pain directement 횪 gauche de l?셙ssiette, jamais dessus. On le rompt avec les mains, plut척t que de le couper au couteau.', next: 'Pr챕parer la mission suivante', wrong: 'Presque !', tryAgain: 'Et si vous essayiez encore ?', options: ['Sur l?셙ssiette', '? gauche de la table', 'Sur la serviette'] }
};

export default function Home() {
  const [lang, setLang] = useState<Lang>('ko'); const [started, setStarted] = useState(false); const [answer, setAnswer] = useState<number | null>(null); const t = copy[lang];
  return <main className="min-h-screen bg-[#f8f2e8] text-[#2d2521]">
    <nav className="mx-auto flex max-w-6xl items-center justify-between px-5 py-5 sm:px-10"><div className="flex items-center gap-2 text-[#6f2637]"><Utensils size={18}/><span className="serif text-lg font-semibold tracking-wide">? TABLE!</span></div><div className="flex items-center gap-3 text-xs font-semibold"><Globe2 size={15} className="text-[#b58b4b]"/><button onClick={()=>setLang('ko')} className={lang==='ko'?'active-lang':''}>KO</button><span className="text-[#c7bcae]">|</span><button onClick={()=>setLang('fr')} className={lang==='fr'?'active-lang':''}>FR</button></div></nav>
    {!started ? <section className="mx-auto grid max-w-6xl items-center gap-10 px-5 pb-16 pt-10 sm:px-10 md:grid-cols-[1.05fr_.95fr] md:pt-20"><div><p className="eyebrow">{t.eyebrow}</p><h1 className="serif mt-5 text-6xl leading-[.9] text-[#6f2637] sm:text-8xl">{t.hero}</h1><p className="mt-7 whitespace-pre-line text-xl leading-relaxed text-[#594c43]">{t.sub}</p><button onClick={()=>setStarted(true)} className="mt-9 flex items-center gap-3 rounded-full bg-[#6f2637] px-6 py-4 text-sm font-bold text-white shadow-lg shadow-[#6f2637]/20 transition hover:-translate-y-1">{t.start}<ArrowRight size={17}/></button><div className="mt-12 flex gap-5 text-sm text-[#8a796b]"><span className="flex items-center gap-2"><Sparkles size={15} className="text-[#b58b4b]"/>5 missions</span><span className="flex items-center gap-2"><ChefHat size={15} className="text-[#b58b4b]"/>{t.tips}</span></div></div><div className="relative mx-auto w-full max-w-md"><div className="hero-art"><div className="plate"><div className="food">??/div></div><div className="wine">??/div><div className="flower">??/div></div><div className="absolute -bottom-4 -left-2 rounded-2xl bg-white/80 px-4 py-3 text-xs shadow-sm backdrop-blur"><span className="block text-[#b58b4b]">BON APP횋TIT</span><span className="text-[#78695e]">{lang==='ko'?'利먭굅???앹궗 ?섏꽭??:'Bon app챕tit !'}</span></div></div></section> : <section className="mx-auto max-w-3xl px-5 pb-16 pt-8 sm:px-10"><div className="mb-10 flex items-center justify-between"><div><p className="eyebrow">{t.progress}</p><div className="mt-3 h-1.5 w-44 rounded-full bg-[#e5d9c9]"><div className="h-full w-1/5 rounded-full bg-[#b58b4b]"/></div></div><span className="serif text-3xl text-[#b58b4b]">01<span className="text-lg text-[#c8bcac"> / 05</span></span></div><div className="quiz-card"><div className="mb-8 flex justify-center"><div className="bread-illustration">?쪝</div></div><div className="text-center"><p className="text-sm text-[#a58f7c]">{t.hint}</p><h2 className="serif mt-3 text-3xl text-[#6f2637] sm:text-4xl">{t.question}</h2></div><div className="mt-8 grid gap-3 sm:grid-cols-3">{t.options.map((option,i)=><button key={option} onClick={()=>setAnswer(i)} className={`option ${answer===i ? (i===1?'correct':'incorrect') : ''}`}><span>{String.fromCharCode(65+i)}</span>{option}</button>)}</div>{answer!==null&&<div className={`result ${answer===1?'result-correct':'result-wrong'}`}>{answer===1?<><Check size={20}/><div><strong>{t.correct}</strong><p>{t.correctSub}</p><button className="tip-button" onClick={()=>{}}>{t.tipTitle} <ArrowRight size={14}/></button></div></>:<><X size={20}/><div><strong>{t.wrong}</strong><p>{t.tryAgain}</p></div></>}</div>}</div><div className="mt-7 flex items-center justify-center gap-2 text-xs text-[#a58f7c]"><LockKeyhole size={13}/> {lang==='ko'?'吏꾪뻾 ?곹솴? ?먮룞?쇰줈 ??λ뤌??:'Votre progression est sauvegard챕e'}</div></section>}
    <footer className="mx-auto flex max-w-6xl items-center justify-between border-t border-[#e4d8c8] px-5 py-6 text-xs text-[#9c8b7d] sm:px-10"><span>짤 2024 ? Table!</span><span className="flex items-center gap-1"><CircleHelp size={14}/> {lang==='ko'?'?꾨옉???앺긽???묒? ?댁빞湲?:'Petites histoires de la table fran챌aise'}</span></footer>
  </main>
}

